# Generated by Django 5.1.6 on 2025-03-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "task", "verbose_name_plural": "tasks"},
        ),
        migrations.AddField(
            model_name="task",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Task description"),
        ),
        migrations.AddField(
            model_name="task",
            name="description_pl",
            field=models.TextField(null=True, verbose_name="Task description"),
        ),
    ]
