# Generated by Django 5.1.6 on 2025-03-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_usertask_completedtask_task_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedtask",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Opublikuj w galerii"),
        ),
        migrations.AddField(
            model_name="completedtask",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Photo"
            ),
        ),
    ]
