# Generated by Django 5.1.6 on 2025-03-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_alter_completedtask_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedtask",
            name="photo",
            field=models.ImageField(upload_to="tasks_photos/", verbose_name="Photo"),
        ),
    ]
