# Generated by Django 5.1.6 on 2025-03-01 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_completedtask_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedtask",
            name="date_completed",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
