# Generated by Django 5.1.6 on 2025-03-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_completedtask_date_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedtask",
            name="task_verified",
            field=models.BooleanField(default=False),
        ),
    ]
