# Generated by Django 5.1.6 on 2025-03-05 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_completedtask_task_verified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmojiReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=10, verbose_name="Emoji")),
                (
                    "completed_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.completedtask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "emoji reaction",
                "verbose_name_plural": "emoji reactions",
                "unique_together": {("user", "completed_task")},
            },
        ),
    ]
